import {MigrationInterface, QueryRunner} from "typeorm";

export class initDB1616538638101 implements MigrationInterface {
    name = 'initDB1616538638101'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "user_type" ("typeId" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, CONSTRAINT "PK_63c74bc82b018bf892f1d191525" PRIMARY KEY ("typeId"))`);
        await queryRunner.query(`CREATE TABLE "user_have_type" ("userHaveTypeId" uuid NOT NULL DEFAULT uuid_generate_v4(), "userUserId" uuid, "typeTypeId" uuid, CONSTRAINT "PK_8d78376e79052d974ab97c88fad" PRIMARY KEY ("userHaveTypeId"))`);
        await queryRunner.query(`CREATE TABLE "insult" ("insultId" uuid NOT NULL DEFAULT uuid_generate_v4(), "text" character varying NOT NULL, "trigger" character varying NOT NULL, CONSTRAINT "PK_106239133449cf36f7261087eae" PRIMARY KEY ("insultId"))`);
        await queryRunner.query(`CREATE TABLE "insult_is_special_for" ("insultIsSpecialForId" uuid NOT NULL DEFAULT uuid_generate_v4(), "userUserId" uuid, "insultInsultId" uuid, CONSTRAINT "PK_71a79192208d05cb6c0c5b94059" PRIMARY KEY ("insultIsSpecialForId"))`);
        await queryRunner.query(`CREATE TABLE "evolution_line" ("evolutionLineId" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, CONSTRAINT "PK_01b23737ea962e3ef009729b7e3" PRIMARY KEY ("evolutionLineId"))`);
        await queryRunner.query(`CREATE TABLE "effect" ("effectId" SERIAL NOT NULL, "name" character varying NOT NULL, "description" character varying NOT NULL, CONSTRAINT "PK_a8f2f6b404d808d8bf4b70e4cbe" PRIMARY KEY ("effectId"))`);
        await queryRunner.query(`CREATE TABLE "move_effect" ("MoveEffectId" uuid NOT NULL DEFAULT uuid_generate_v4(), "intencity" integer NOT NULL, "duration" integer NOT NULL, "moveMoveId" uuid, "effectEffectId" integer, CONSTRAINT "PK_00fb87f7e1c4d798a0e7b599797" PRIMARY KEY ("MoveEffectId"))`);
        await queryRunner.query(`CREATE TABLE "move_synergie" ("moveSynergieId" uuid NOT NULL DEFAULT uuid_generate_v4(), "moveMoveId" uuid, "moveSynergieMoveId" uuid, CONSTRAINT "PK_dbe6245103da9dcd653ffa9cbd4" PRIMARY KEY ("moveSynergieId"))`);
        await queryRunner.query(`CREATE TABLE "type_effect" ("TypeEffectId" uuid NOT NULL DEFAULT uuid_generate_v4(), "coefficient" integer NOT NULL, "fromTypeTypeId" uuid, "toTypeTypeId" uuid, CONSTRAINT "PK_c91ec832c7ff9f9c8f3b95be281" PRIMARY KEY ("TypeEffectId"))`);
        await queryRunner.query(`CREATE TABLE "type" ("typeId" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "moveWithSynergieTypeMoveId" uuid, "movesMoveId" uuid, "temtemFirstTypeTeitemId" uuid, "temtemSecondTypeTeitemId" uuid, CONSTRAINT "PK_3a25b3b7490c51932eb4d7b6491" PRIMARY KEY ("typeId"))`);
        await queryRunner.query(`CREATE TABLE "user_temtem_have_move" ("userTemtemHaveMoveId" uuid NOT NULL DEFAULT uuid_generate_v4(), "method" integer NOT NULL, "userTemtemUserTemtemId" uuid, "moveMoveId" uuid, CONSTRAINT "PK_cb40a5e293a424d46cd0de7a1d8" PRIMARY KEY ("userTemtemHaveMoveId"))`);
        await queryRunner.query(`CREATE TABLE "move" ("moveId" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "haveSynergie" boolean NOT NULL, "damage" integer NOT NULL, "stamina" integer NOT NULL, "hold" integer NOT NULL, "priority" real NOT NULL, "class" integer NOT NULL, "Target" integer NOT NULL, CONSTRAINT "PK_9cf37e1209d3e3c05dc55dccbc4" PRIMARY KEY ("moveId"))`);
        await queryRunner.query(`CREATE TABLE "egg_move_giver" ("eggMoveGiverId" uuid NOT NULL DEFAULT uuid_generate_v4(), "temtemGiverTeitemId" uuid, "moveMoveId" uuid, "temtemReciverTemtemHaveMove" uuid, CONSTRAINT "PK_49c9a19f5f564ed21ac8361e8a7" PRIMARY KEY ("eggMoveGiverId"))`);
        await queryRunner.query(`CREATE TABLE "temtem_have_move" ("temtemHaveMove" uuid NOT NULL DEFAULT uuid_generate_v4(), "method" integer NOT NULL, "temtemTeitemId" uuid, "moveMoveId" uuid, CONSTRAINT "PK_1ccdc61620671e73a5cd43982a0" PRIMARY KEY ("temtemHaveMove"))`);
        await queryRunner.query(`CREATE TABLE "trait" ("traitId" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "description" character varying NOT NULL, CONSTRAINT "PK_f8bce007639872c53c814de5896" PRIMARY KEY ("traitId"))`);
        await queryRunner.query(`CREATE TABLE "temtem_have_trait" ("temtemHaveTraitId" uuid NOT NULL DEFAULT uuid_generate_v4(), "temtemTeitemId" uuid, "traitTraitId" uuid, CONSTRAINT "PK_5aa53b6e2a428bfde0b5b6330a3" PRIMARY KEY ("temtemHaveTraitId"))`);
        await queryRunner.query(`CREATE TABLE "temtem_image" ("temtemImageId" uuid NOT NULL DEFAULT uuid_generate_v4(), "path" character varying NOT NULL, "name" character varying NOT NULL, "useCase" integer NOT NULL, "temtemTeitemId" uuid, CONSTRAINT "PK_6c2a22b308619267930c0aa2674" PRIMARY KEY ("temtemImageId"))`);
        await queryRunner.query(`CREATE TABLE "location" ("locationId" uuid NOT NULL DEFAULT uuid_generate_v4(), "location" character varying NOT NULL, "trigger" character varying, "isReserved" boolean NOT NULL, CONSTRAINT "PK_8b51e14a3447c3df460c1907acb" PRIMARY KEY ("locationId"))`);
        await queryRunner.query(`CREATE TABLE "temtem_location_possibility" ("temtemLocationPossibilityId" uuid NOT NULL DEFAULT uuid_generate_v4(), "rate" integer NOT NULL, "locationLocationId" uuid, "temtemTeitemId" uuid, CONSTRAINT "PK_4f0e6c137be0dd34d4df4f6c4be" PRIMARY KEY ("temtemLocationPossibilityId"))`);
        await queryRunner.query(`CREATE TABLE "temtem" ("teitemId" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "inGameId" integer NOT NULL, "publishDate" date, "catchRate" integer, "tvYield" character varying, "maleRate" integer NOT NULL, "femaleRate" integer NOT NULL, "hp" integer NOT NULL, "sta" integer NOT NULL, "speed" integer NOT NULL, "atk" integer NOT NULL, "def" integer NOT NULL, "speatk" integer NOT NULL, "spedef" integer NOT NULL, "evolutionLineEvolutionLineId" uuid, "firstTypeTypeId" uuid, "secondTypeTypeId" uuid, CONSTRAINT "PK_6884d56fdd013fdc9a497f38d33" PRIMARY KEY ("teitemId"))`);
        await queryRunner.query(`CREATE TABLE "item" ("itemId" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "price" integer, CONSTRAINT "PK_51d980088ed0b9a65dc50c94e92" PRIMARY KEY ("itemId"))`);
        await queryRunner.query(`CREATE TABLE "reproduction" ("reproductionId" uuid NOT NULL DEFAULT uuid_generate_v4(), "date" TIMESTAMP NOT NULL, "fertFemale" integer NOT NULL, "fertMale" integer NOT NULL, "tier" integer NOT NULL, "totalPrice" integer NOT NULL, "fatherUserTemtemId" uuid, "motherUserTemtemId" uuid, "itemMaleItemId" uuid, "itemFemaleItemId" uuid, CONSTRAINT "PK_009e9bb39cf68b15005058688b0" PRIMARY KEY ("reproductionId"))`);
        await queryRunner.query(`CREATE TABLE "user_temtem" ("userTemtemId" uuid NOT NULL DEFAULT uuid_generate_v4(), "rename" character varying, "card" character varying NOT NULL, "originalTamer" character varying, "lvl" integer NOT NULL, "luma" boolean NOT NULL DEFAULT false, "sexe" integer NOT NULL, "fetility" integer NOT NULL, "isEgg" boolean NOT NULL DEFAULT false, "svHp" integer NOT NULL, "svSta" integer NOT NULL, "svSpeed" integer NOT NULL, "svAtk" integer NOT NULL, "svDef" integer NOT NULL, "svSpeatk" integer NOT NULL, "svSpedef" integer NOT NULL, "tvHp" integer NOT NULL, "tvSta" integer NOT NULL, "tvSpeed" integer NOT NULL, "tvAtk" integer NOT NULL, "tvDef" integer NOT NULL, "tvSpeatk" integer NOT NULL, "tvSpedef" integer NOT NULL, "userUserId" uuid, "temtemTeitemId" uuid, "findInLocationId" uuid, "additionalTypeTypeId" uuid, CONSTRAINT "PK_f9932cfb36a85107286eebdf67f" PRIMARY KEY ("userTemtemId"))`);
        await queryRunner.query(`CREATE TABLE "clan" ("clanId" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "bannerImage" character varying NOT NULL, "pansunsFund" integer NOT NULL, CONSTRAINT "PK_44f47996b2a5199c030423a4156" PRIMARY KEY ("clanId"))`);
        await queryRunner.query(`CREATE TABLE "user_clan" ("userClanId" uuid NOT NULL DEFAULT uuid_generate_v4(), "userUserId" uuid, "clanClanId" uuid, CONSTRAINT "PK_587e099bec74561636de29a0d30" PRIMARY KEY ("userClanId"))`);
        await queryRunner.query(`CREATE TABLE "user_item" ("userItemId" uuid NOT NULL DEFAULT uuid_generate_v4(), "userUserId" uuid, "itemItemId" uuid, CONSTRAINT "PK_0d5e849cf42c1c7a57f71bcf082" PRIMARY KEY ("userItemId"))`);
        await queryRunner.query(`CREATE TABLE "item_transaction" ("itemTransactionId" uuid NOT NULL DEFAULT uuid_generate_v4(), "itemItemId" uuid, "paymentPaymentId" uuid, CONSTRAINT "PK_3647a1922ab91a9a62b0af43830" PRIMARY KEY ("itemTransactionId"))`);
        await queryRunner.query(`CREATE TABLE "temtem_transaction" ("temtemTransactionId" uuid NOT NULL DEFAULT uuid_generate_v4(), "paymentPaymentId" uuid, "userTemtemUserTemtemId" uuid, CONSTRAINT "PK_6196413d2b761e66cde183d1fed" PRIMARY KEY ("temtemTransactionId"))`);
        await queryRunner.query(`CREATE TABLE "payment" ("paymentId" uuid NOT NULL DEFAULT uuid_generate_v4(), "authorPansuns" integer NOT NULL, "withUserPansuns" integer NOT NULL, "authorUserId" uuid, "withUserUserId" uuid, CONSTRAINT "PK_67ee4523b649947b6a7954dc673" PRIMARY KEY ("paymentId"))`);
        await queryRunner.query(`CREATE TABLE "user" ("UserId" uuid NOT NULL DEFAULT uuid_generate_v4(), "firstName" character varying NOT NULL, "lastName" character varying NOT NULL, "inGamePseudo" character varying NOT NULL, "email" character varying NOT NULL, "password" character varying NOT NULL, "idDiscord" character varying, "tokenVersion" integer NOT NULL, "pansuns" integer NOT NULL, "aliasAliasId" uuid, CONSTRAINT "PK_825656fb054dbb121350ba0d9da" PRIMARY KEY ("UserId"))`);
        await queryRunner.query(`CREATE TABLE "alias" ("AliasId" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, CONSTRAINT "PK_804fd1e5c5dc0cbaa0a9ead8b46" PRIMARY KEY ("AliasId"))`);
        await queryRunner.query(`ALTER TABLE "user_have_type" ADD CONSTRAINT "FK_a0ade8eff357e06a070ba48bb6d" FOREIGN KEY ("userUserId") REFERENCES "user"("UserId") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_have_type" ADD CONSTRAINT "FK_4b861a9ef39e4606797c41ac830" FOREIGN KEY ("typeTypeId") REFERENCES "user_type"("typeId") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "insult_is_special_for" ADD CONSTRAINT "FK_cfaf3f6c3114d4c4846f6feae37" FOREIGN KEY ("userUserId") REFERENCES "user"("UserId") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "insult_is_special_for" ADD CONSTRAINT "FK_08c4fef01c08d8ab5db08e784f9" FOREIGN KEY ("insultInsultId") REFERENCES "insult"("insultId") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "move_effect" ADD CONSTRAINT "FK_4e5ed0298956254b4840d64fcfa" FOREIGN KEY ("moveMoveId") REFERENCES "move"("moveId") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "move_effect" ADD CONSTRAINT "FK_1c3d4f4ae78711161a998ef11da" FOREIGN KEY ("effectEffectId") REFERENCES "effect"("effectId") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "move_synergie" ADD CONSTRAINT "FK_b1ac8fe451256166fb2863059b1" FOREIGN KEY ("moveMoveId") REFERENCES "move"("moveId") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "move_synergie" ADD CONSTRAINT "FK_71529d7525c112fcc5641e11bbb" FOREIGN KEY ("moveSynergieMoveId") REFERENCES "move"("moveId") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "type_effect" ADD CONSTRAINT "FK_b5d08e8ee3917beb8d9bd670395" FOREIGN KEY ("fromTypeTypeId") REFERENCES "type"("typeId") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "type_effect" ADD CONSTRAINT "FK_37f8fd1ce4bcb42c97893f0c09a" FOREIGN KEY ("toTypeTypeId") REFERENCES "type"("typeId") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "type" ADD CONSTRAINT "FK_21aaaf85c32f6c9c01ab5b20b2a" FOREIGN KEY ("moveWithSynergieTypeMoveId") REFERENCES "move"("moveId") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "type" ADD CONSTRAINT "FK_8bd299711e2e1f777f24d2ef754" FOREIGN KEY ("movesMoveId") REFERENCES "move"("moveId") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "type" ADD CONSTRAINT "FK_b9da205837881bed617ea766711" FOREIGN KEY ("temtemFirstTypeTeitemId") REFERENCES "temtem"("teitemId") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "type" ADD CONSTRAINT "FK_a5758de7638fd62a6965117e90e" FOREIGN KEY ("temtemSecondTypeTeitemId") REFERENCES "temtem"("teitemId") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_temtem_have_move" ADD CONSTRAINT "FK_022229a95c715588fd6834dcbc5" FOREIGN KEY ("userTemtemUserTemtemId") REFERENCES "user_temtem"("userTemtemId") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_temtem_have_move" ADD CONSTRAINT "FK_3677fe7a2c75509343ae5ea1475" FOREIGN KEY ("moveMoveId") REFERENCES "move"("moveId") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "egg_move_giver" ADD CONSTRAINT "FK_844b2be3984a742d4da40e19c5d" FOREIGN KEY ("temtemGiverTeitemId") REFERENCES "temtem"("teitemId") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "egg_move_giver" ADD CONSTRAINT "FK_557297aad66d8e3a59f943b74b9" FOREIGN KEY ("moveMoveId") REFERENCES "move"("moveId") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "egg_move_giver" ADD CONSTRAINT "FK_fc7dd5793c5c6e59aa307fc7a82" FOREIGN KEY ("temtemReciverTemtemHaveMove") REFERENCES "temtem_have_move"("temtemHaveMove") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "temtem_have_move" ADD CONSTRAINT "FK_902a7af2f94a3b2b52b208fdfc9" FOREIGN KEY ("temtemTeitemId") REFERENCES "temtem"("teitemId") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "temtem_have_move" ADD CONSTRAINT "FK_e4c59719ea4428c30ac98995674" FOREIGN KEY ("moveMoveId") REFERENCES "move"("moveId") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "temtem_have_trait" ADD CONSTRAINT "FK_c424fe8dc1c4692f612c51f4545" FOREIGN KEY ("temtemTeitemId") REFERENCES "temtem"("teitemId") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "temtem_have_trait" ADD CONSTRAINT "FK_cc7a32b2f5c76c9137bebe623b8" FOREIGN KEY ("traitTraitId") REFERENCES "trait"("traitId") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "temtem_image" ADD CONSTRAINT "FK_b141f853314d276fd5d87486c08" FOREIGN KEY ("temtemTeitemId") REFERENCES "temtem"("teitemId") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "temtem_location_possibility" ADD CONSTRAINT "FK_dfa9ffd84c1d9914dd695f4b2bb" FOREIGN KEY ("locationLocationId") REFERENCES "location"("locationId") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "temtem_location_possibility" ADD CONSTRAINT "FK_0c7d70192b8ebbf15160d13f913" FOREIGN KEY ("temtemTeitemId") REFERENCES "temtem"("teitemId") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "temtem" ADD CONSTRAINT "FK_76c23c448056b47d94dd03094fa" FOREIGN KEY ("evolutionLineEvolutionLineId") REFERENCES "evolution_line"("evolutionLineId") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "temtem" ADD CONSTRAINT "FK_7613318defb291a0dbe376bffd9" FOREIGN KEY ("firstTypeTypeId") REFERENCES "type"("typeId") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "temtem" ADD CONSTRAINT "FK_e1b63f9d3c07cdb8edbba4de3de" FOREIGN KEY ("secondTypeTypeId") REFERENCES "type"("typeId") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "reproduction" ADD CONSTRAINT "FK_c052d4755849fffeb519e056a8c" FOREIGN KEY ("fatherUserTemtemId") REFERENCES "user_temtem"("userTemtemId") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "reproduction" ADD CONSTRAINT "FK_95cb8ca50135d2d655ae3cf5527" FOREIGN KEY ("motherUserTemtemId") REFERENCES "user_temtem"("userTemtemId") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "reproduction" ADD CONSTRAINT "FK_03fe386e61626dbc3d1fb977115" FOREIGN KEY ("itemMaleItemId") REFERENCES "item"("itemId") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "reproduction" ADD CONSTRAINT "FK_bea02f0ee542633e322cec024ce" FOREIGN KEY ("itemFemaleItemId") REFERENCES "item"("itemId") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_temtem" ADD CONSTRAINT "FK_4c49f0a3384644e5ec95a3ea0bb" FOREIGN KEY ("userUserId") REFERENCES "user"("UserId") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_temtem" ADD CONSTRAINT "FK_257b3b764ba281de8e563c4f599" FOREIGN KEY ("temtemTeitemId") REFERENCES "temtem"("teitemId") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_temtem" ADD CONSTRAINT "FK_e294180155ae1d54e2ca26ea818" FOREIGN KEY ("findInLocationId") REFERENCES "location"("locationId") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_temtem" ADD CONSTRAINT "FK_1840f7fab2f64cf67240c07c700" FOREIGN KEY ("additionalTypeTypeId") REFERENCES "type"("typeId") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_clan" ADD CONSTRAINT "FK_ce14bdf46c67af356848be0bf0f" FOREIGN KEY ("userUserId") REFERENCES "user"("UserId") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_clan" ADD CONSTRAINT "FK_1d8fe05d17e3ae13553905f5988" FOREIGN KEY ("clanClanId") REFERENCES "clan"("clanId") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_item" ADD CONSTRAINT "FK_c2cf87b1d87be8424f88cf45fd7" FOREIGN KEY ("userUserId") REFERENCES "user"("UserId") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_item" ADD CONSTRAINT "FK_9b2b93150dadb00a6deca6ccf4b" FOREIGN KEY ("itemItemId") REFERENCES "item"("itemId") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "item_transaction" ADD CONSTRAINT "FK_45b4651b081448d8ae1fbc9a2d6" FOREIGN KEY ("itemItemId") REFERENCES "item"("itemId") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "item_transaction" ADD CONSTRAINT "FK_08e6b712ea2ba2b048ec7d5b212" FOREIGN KEY ("paymentPaymentId") REFERENCES "payment"("paymentId") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "temtem_transaction" ADD CONSTRAINT "FK_1bf7e7a2d42ac54387cb3e9c850" FOREIGN KEY ("paymentPaymentId") REFERENCES "payment"("paymentId") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "temtem_transaction" ADD CONSTRAINT "FK_566bd9ef050cc453f3d346b472e" FOREIGN KEY ("userTemtemUserTemtemId") REFERENCES "user_temtem"("userTemtemId") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "payment" ADD CONSTRAINT "FK_bae7e4cbeed2eb2acfca3ccdadd" FOREIGN KEY ("authorUserId") REFERENCES "user"("UserId") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "payment" ADD CONSTRAINT "FK_4090bddef8ebd22febf642e93c1" FOREIGN KEY ("withUserUserId") REFERENCES "user"("UserId") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user" ADD CONSTRAINT "FK_3992d71cc4e3b6be2df4efde1fd" FOREIGN KEY ("aliasAliasId") REFERENCES "alias"("AliasId") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "user" DROP CONSTRAINT "FK_3992d71cc4e3b6be2df4efde1fd"`);
        await queryRunner.query(`ALTER TABLE "payment" DROP CONSTRAINT "FK_4090bddef8ebd22febf642e93c1"`);
        await queryRunner.query(`ALTER TABLE "payment" DROP CONSTRAINT "FK_bae7e4cbeed2eb2acfca3ccdadd"`);
        await queryRunner.query(`ALTER TABLE "temtem_transaction" DROP CONSTRAINT "FK_566bd9ef050cc453f3d346b472e"`);
        await queryRunner.query(`ALTER TABLE "temtem_transaction" DROP CONSTRAINT "FK_1bf7e7a2d42ac54387cb3e9c850"`);
        await queryRunner.query(`ALTER TABLE "item_transaction" DROP CONSTRAINT "FK_08e6b712ea2ba2b048ec7d5b212"`);
        await queryRunner.query(`ALTER TABLE "item_transaction" DROP CONSTRAINT "FK_45b4651b081448d8ae1fbc9a2d6"`);
        await queryRunner.query(`ALTER TABLE "user_item" DROP CONSTRAINT "FK_9b2b93150dadb00a6deca6ccf4b"`);
        await queryRunner.query(`ALTER TABLE "user_item" DROP CONSTRAINT "FK_c2cf87b1d87be8424f88cf45fd7"`);
        await queryRunner.query(`ALTER TABLE "user_clan" DROP CONSTRAINT "FK_1d8fe05d17e3ae13553905f5988"`);
        await queryRunner.query(`ALTER TABLE "user_clan" DROP CONSTRAINT "FK_ce14bdf46c67af356848be0bf0f"`);
        await queryRunner.query(`ALTER TABLE "user_temtem" DROP CONSTRAINT "FK_1840f7fab2f64cf67240c07c700"`);
        await queryRunner.query(`ALTER TABLE "user_temtem" DROP CONSTRAINT "FK_e294180155ae1d54e2ca26ea818"`);
        await queryRunner.query(`ALTER TABLE "user_temtem" DROP CONSTRAINT "FK_257b3b764ba281de8e563c4f599"`);
        await queryRunner.query(`ALTER TABLE "user_temtem" DROP CONSTRAINT "FK_4c49f0a3384644e5ec95a3ea0bb"`);
        await queryRunner.query(`ALTER TABLE "reproduction" DROP CONSTRAINT "FK_bea02f0ee542633e322cec024ce"`);
        await queryRunner.query(`ALTER TABLE "reproduction" DROP CONSTRAINT "FK_03fe386e61626dbc3d1fb977115"`);
        await queryRunner.query(`ALTER TABLE "reproduction" DROP CONSTRAINT "FK_95cb8ca50135d2d655ae3cf5527"`);
        await queryRunner.query(`ALTER TABLE "reproduction" DROP CONSTRAINT "FK_c052d4755849fffeb519e056a8c"`);
        await queryRunner.query(`ALTER TABLE "temtem" DROP CONSTRAINT "FK_e1b63f9d3c07cdb8edbba4de3de"`);
        await queryRunner.query(`ALTER TABLE "temtem" DROP CONSTRAINT "FK_7613318defb291a0dbe376bffd9"`);
        await queryRunner.query(`ALTER TABLE "temtem" DROP CONSTRAINT "FK_76c23c448056b47d94dd03094fa"`);
        await queryRunner.query(`ALTER TABLE "temtem_location_possibility" DROP CONSTRAINT "FK_0c7d70192b8ebbf15160d13f913"`);
        await queryRunner.query(`ALTER TABLE "temtem_location_possibility" DROP CONSTRAINT "FK_dfa9ffd84c1d9914dd695f4b2bb"`);
        await queryRunner.query(`ALTER TABLE "temtem_image" DROP CONSTRAINT "FK_b141f853314d276fd5d87486c08"`);
        await queryRunner.query(`ALTER TABLE "temtem_have_trait" DROP CONSTRAINT "FK_cc7a32b2f5c76c9137bebe623b8"`);
        await queryRunner.query(`ALTER TABLE "temtem_have_trait" DROP CONSTRAINT "FK_c424fe8dc1c4692f612c51f4545"`);
        await queryRunner.query(`ALTER TABLE "temtem_have_move" DROP CONSTRAINT "FK_e4c59719ea4428c30ac98995674"`);
        await queryRunner.query(`ALTER TABLE "temtem_have_move" DROP CONSTRAINT "FK_902a7af2f94a3b2b52b208fdfc9"`);
        await queryRunner.query(`ALTER TABLE "egg_move_giver" DROP CONSTRAINT "FK_fc7dd5793c5c6e59aa307fc7a82"`);
        await queryRunner.query(`ALTER TABLE "egg_move_giver" DROP CONSTRAINT "FK_557297aad66d8e3a59f943b74b9"`);
        await queryRunner.query(`ALTER TABLE "egg_move_giver" DROP CONSTRAINT "FK_844b2be3984a742d4da40e19c5d"`);
        await queryRunner.query(`ALTER TABLE "user_temtem_have_move" DROP CONSTRAINT "FK_3677fe7a2c75509343ae5ea1475"`);
        await queryRunner.query(`ALTER TABLE "user_temtem_have_move" DROP CONSTRAINT "FK_022229a95c715588fd6834dcbc5"`);
        await queryRunner.query(`ALTER TABLE "type" DROP CONSTRAINT "FK_a5758de7638fd62a6965117e90e"`);
        await queryRunner.query(`ALTER TABLE "type" DROP CONSTRAINT "FK_b9da205837881bed617ea766711"`);
        await queryRunner.query(`ALTER TABLE "type" DROP CONSTRAINT "FK_8bd299711e2e1f777f24d2ef754"`);
        await queryRunner.query(`ALTER TABLE "type" DROP CONSTRAINT "FK_21aaaf85c32f6c9c01ab5b20b2a"`);
        await queryRunner.query(`ALTER TABLE "type_effect" DROP CONSTRAINT "FK_37f8fd1ce4bcb42c97893f0c09a"`);
        await queryRunner.query(`ALTER TABLE "type_effect" DROP CONSTRAINT "FK_b5d08e8ee3917beb8d9bd670395"`);
        await queryRunner.query(`ALTER TABLE "move_synergie" DROP CONSTRAINT "FK_71529d7525c112fcc5641e11bbb"`);
        await queryRunner.query(`ALTER TABLE "move_synergie" DROP CONSTRAINT "FK_b1ac8fe451256166fb2863059b1"`);
        await queryRunner.query(`ALTER TABLE "move_effect" DROP CONSTRAINT "FK_1c3d4f4ae78711161a998ef11da"`);
        await queryRunner.query(`ALTER TABLE "move_effect" DROP CONSTRAINT "FK_4e5ed0298956254b4840d64fcfa"`);
        await queryRunner.query(`ALTER TABLE "insult_is_special_for" DROP CONSTRAINT "FK_08c4fef01c08d8ab5db08e784f9"`);
        await queryRunner.query(`ALTER TABLE "insult_is_special_for" DROP CONSTRAINT "FK_cfaf3f6c3114d4c4846f6feae37"`);
        await queryRunner.query(`ALTER TABLE "user_have_type" DROP CONSTRAINT "FK_4b861a9ef39e4606797c41ac830"`);
        await queryRunner.query(`ALTER TABLE "user_have_type" DROP CONSTRAINT "FK_a0ade8eff357e06a070ba48bb6d"`);
        await queryRunner.query(`DROP TABLE "alias"`);
        await queryRunner.query(`DROP TABLE "user"`);
        await queryRunner.query(`DROP TABLE "payment"`);
        await queryRunner.query(`DROP TABLE "temtem_transaction"`);
        await queryRunner.query(`DROP TABLE "item_transaction"`);
        await queryRunner.query(`DROP TABLE "user_item"`);
        await queryRunner.query(`DROP TABLE "user_clan"`);
        await queryRunner.query(`DROP TABLE "clan"`);
        await queryRunner.query(`DROP TABLE "user_temtem"`);
        await queryRunner.query(`DROP TABLE "reproduction"`);
        await queryRunner.query(`DROP TABLE "item"`);
        await queryRunner.query(`DROP TABLE "temtem"`);
        await queryRunner.query(`DROP TABLE "temtem_location_possibility"`);
        await queryRunner.query(`DROP TABLE "location"`);
        await queryRunner.query(`DROP TABLE "temtem_image"`);
        await queryRunner.query(`DROP TABLE "temtem_have_trait"`);
        await queryRunner.query(`DROP TABLE "trait"`);
        await queryRunner.query(`DROP TABLE "temtem_have_move"`);
        await queryRunner.query(`DROP TABLE "egg_move_giver"`);
        await queryRunner.query(`DROP TABLE "move"`);
        await queryRunner.query(`DROP TABLE "user_temtem_have_move"`);
        await queryRunner.query(`DROP TABLE "type"`);
        await queryRunner.query(`DROP TABLE "type_effect"`);
        await queryRunner.query(`DROP TABLE "move_synergie"`);
        await queryRunner.query(`DROP TABLE "move_effect"`);
        await queryRunner.query(`DROP TABLE "effect"`);
        await queryRunner.query(`DROP TABLE "evolution_line"`);
        await queryRunner.query(`DROP TABLE "insult_is_special_for"`);
        await queryRunner.query(`DROP TABLE "insult"`);
        await queryRunner.query(`DROP TABLE "user_have_type"`);
        await queryRunner.query(`DROP TABLE "user_type"`);
    }

}
